'use client';
import {useState,useEffect,useRef} from 'react';
import HeroPortrait from './HeroPortrait';
import TechOrbit from './TechOrbit';
import {BrandLogo,TechLabel,TechText} from './Technology';
const heroIntroSource = '/intro.webm';
import {ArrowUpRight,ArrowDown,ArrowRight,Plus,X,Menu, GitFork,UserRound,Camera,Mail,MoveUpRight,VolumeX,Orbit,Check,Copy} from 'lucide-react';
const email='contact.kumailraza@gmail.com';
type Project={name:string;category:string;subtitle:string;description:string;stack:string[];features:string[];image?:string;live?:string;code?:string;visual:string};
const projects:Project[]=[
{name:'Real Estate Operations',category:'Full stack',subtitle:'One platform. Every property workflow.',description:'A SaaS platform connecting lead management, CRM, property operations and everyday business workflows.',stack:['React','TypeScript','Node.js','Supabase','PostgreSQL'],features:['Lead Center and CRM','Property and task management','Calendar, reporting and workflow automation'],image:'/realestate.png',live:'https://real-estate-automation-agent.onrender.com/',code:'https://github.com/kumailraza5/Real-Estate-Automation-Agent',visual:'estate'},
{name:'Zeina Atelier',category:'Shopify',subtitle:'An editorial storefront for wedding stationery.',description:'Custom Shopify OS 2.0 theme work for a refined wedding stationery brand. Warm neutrals, expressive collections and reusable sections.',stack:['Shopify','Liquid','JavaScript','CSS'],features:['Custom homepage, Edits and collection layouts','Product colour options and navigation','Responsive storefront and cart troubleshooting'],image:'/zeina-atelier.png',visual:'zeina'},
{name:'Event Management System',category:'Full stack',subtitle:'From discovery to the final QR check-in.',description:'A role-based event platform for admins, organizers and attendees, with booking, feedback and data-driven planning.',stack:['React','Express','Supabase','Tailwind'],features:['Event creation, approval, registration and QR tickets','Date-based event lifecycle and organizer rankings','Analytics, PKR pricing analysis and data-driven planner'],visual:'events'},
{name:'Smart Exam Generator',category:'AI & automation',subtitle:'A smarter way to build and manage exams.',description:'A rule-based paper generation system with difficulty-balanced question allocation and connected teacher/student workflows.',stack:['Python','Flask','MySQL','JavaScript'],features:['Admin, Teacher and Student roles','Question allocation by difficulty','Assign exams, take papers and grade results'],visual:'exam'},
{name:'Aurevo Store',category:'Full stack',subtitle:'Premium products. A considered shopping experience.',description:'A responsive e-commerce experience for watches and perfumes, with database integration, authentication and cart workflows.',stack:['React','TypeScript','Supabase'],features:['Product browsing and cart','Account authentication','Responsive storefront'],image:'/aurevo.png',live:'https://aurevostore.pk/',code:'https://github.com/kumailraza5/Aurevo.store',visual:'aurevo'},
{name:'Restaurant Voice Agent',category:'AI & automation',subtitle:'Turning conversations into connected workflows.',description:'Voice agent workflow design for restaurant calls, menu questions and order handoff, connected to business data.',stack:['Node.js','Python','Supabase','AI APIs'],features:['Inbound menu Q&A and order-taking flows','Kitchen order handoff','Outbound feedback and customer workflows'],visual:'voice'},
{name:'USP OBE System',category:'Full stack',subtitle:'Learning outcomes, made measurable.',description:'An education platform connecting courses, assessments and learning outcomes through role-based dashboards.',stack:['React','TypeScript','Node.js','Supabase'],features:['CLO and PLO mapping','Student, teacher and admin workflows','Assessment and outcome dashboards'],image:'/obe.png',live:'https://obe-system-w2wd.onrender.com/',code:'https://github.com/kumailraza5/OBE-System',visual:'obe'},
{name:'ScentedVenture',category:'Shopify',subtitle:'The details that make a storefront feel finished.',description:'Shopify theme cleanup and storefront improvements across product templates, navigation, forms and brand elements.',stack:['Shopify','Liquid','JavaScript'],features:['Theme and demo popup cleanup','Newsletter and contact form improvements','Footer, social sharing and navigation refinements'],image:'/scentedventure.jpg',live:'https://scentedventure.com/',visual:'scent'},
{name:'Classroom Gadget Detection',category:'AI & automation',subtitle:'Computer vision for exam environments.',description:'A real-time computer vision project focused on electronic gadgets, small papers and posture-based monitoring.',stack:['Python','YOLO','Computer vision'],features:['Phone and electronic gadget detection','Small paper/chit detection work','Dataset training, optimization and face orientation logic'],visual:'vision'},
{name:'Elite Motors',category:'Full stack',subtitle:'A showroom experience, reimagined for the web.',description:'An animated luxury car showroom interface with responsive vehicle listings and a clean presentation.',stack:['React','TypeScript','Tailwind','Framer Motion'],features:['Interactive vehicle listings','Motion-led interface','Responsive showroom layouts'],image:'/motors.png',live:'https://carshowroom-ws42.onrender.com/',code:'https://github.com/kumailraza5/carshowroom_UI',visual:'motors'}
];
function Artwork({p}:{p:Project}){return p.image?<img src={p.image} alt={`${p.name} project screenshot`} loading="lazy"/>:<div className={`artwork ${p.visual}`} aria-label={`${p.name} illustrative project artwork`}><span className="art-label">{p.category==='Shopify'?'STOREFRONT DESIGN':'PROJECT CONCEPT'}</span>{p.visual==='zeina'?<><div className="stationery sheet"><small>THE WEDDING OF</small><i>Amelia<br/>& Oliver</i><span>YOU ARE INVITED</span></div><div className="stationery back"><i>Z</i><span>ZEINA ATELIER</span></div></>:p.visual==='scent'?<><div className="bottle"><div/><i>S</i><span>SCENTED<br/>VENTURE</span></div><em className="scent-word">a little<br/>everyday luxury.</em></>:p.visual==='events'?<><div className="event-ticket"><span>EVENT MANAGEMENT</span><h4>Make it<br/>an occasion.</h4><div className="ticket-bottom"><b>ADMIT ONE</b><div className="qr"/></div></div><div className="ticket-orbit"/></>:p.visual==='voice'?<><div className="soundwave">{Array.from({length:30},(_,i)=><i key={i} style={{height:`${20+Math.sin(i*.7)**2*90}px`,animationDelay:`${i*.05}s`}}/>)}</div><div className="voice-label"><span className="dot"/> CONVERSATION → ACTION</div></>:p.visual==='vision'?<><div className="scan"><div className="scan-line"/><div className="detected">PHONE <span>.94</span></div><Orbit size={100}/></div></>:<div className="exam-sheet"><span>PAPER GENERATOR / 01</span><h4>Better balance.<br/>Smarter papers.</h4>{['Easy','Medium','Hard'].map((x,i)=><div key={x}><b>{x}</b><i style={{width:`${75-i*20}%`}}/></div>)}</div>}</div>}
export default function Portfolio(){const [category,setCategory]=useState('All work');const [selected,setSelected]=useState<Project|null>(null);const [menu,setMenu]=useState(false);const [motion,setMotion]=useState(true);const [copied,setCopied]=useState(false);const [showAll,setShowAll]=useState(false);const hero=useRef<HTMLElement>(null);
useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)setMotion(false);const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));return()=>observer.disconnect()},[]);
useEffect(()=>{document.documentElement.dataset.motion=motion?'on':'off'},[motion]);
useEffect(()=>{if(!selected)return;const previous=document.activeElement as HTMLElement|null;const old=document.body.style.overflow;document.body.style.overflow='hidden';const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'){const items=Array.from(document.querySelectorAll<HTMLElement>('.modal button, .modal a[href]'));const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',onKey);return()=>{document.body.style.overflow=old;previous?.focus();window.removeEventListener('keydown',onKey)}},[selected]);
const filtered=projects.filter(p=>category==='All work'||p.category===category);const visible=showAll?filtered:filtered.slice(0,6);
const copy=async()=>{try{await navigator.clipboard.writeText(email);setCopied(true);setTimeout(()=>setCopied(false),2200)}catch{window.location.href=`mailto:${email}`}};
return <main><div className="scroll-progress"/><header><a className="brand" href="#home" aria-label="Kumail home">kr<span>®</span></a><nav className={menu?'open':''} aria-label="Main navigation">{[['Work','work'],['Expertise','expertise'],['About','about']].map(([x,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{x}</a>)}</nav><a className="nav-contact" href="#contact">Let’s talk <ArrowUpRight size={15}/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
<section id="home" className="hero" ref={hero} onPointerMove={e=>{if(!motion||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--mx',`${(e.clientX-r.left-r.width/2)/r.width*14}deg`);e.currentTarget.style.setProperty('--my',`${-(e.clientY-r.top-r.height/2)/r.height*9}deg`)}} onPointerLeave={e=>{e.currentTarget.style.setProperty('--mx','0deg');e.currentTarget.style.setProperty('--my','0deg')}}>
<div className="hero-meta"><span><span className="dot"/> AVAILABLE FOR PROJECTS</span><span>PAKISTAN · WORKING WORLDWIDE</span></div><div className="hero-title"><div className="eyebrow">KUMAIL RAZA · <TechText text="FULL STACK & SHOPIFY"/></div><h1>DEVELOPER</h1></div><div className="portrait-stage"><TechOrbit motion={motion}/><div className="halo"/><HeroPortrait src={heroIntroSource}/></div><div className="hero-bottom"><p>I build thoughtful web applications,<br/>distinctive storefronts and intelligent<br/>workflows. From first idea to launch.</p><a className="pill lime" href="#work">Explore my work <ArrowDown size={18}/></a><a className="scroll-hint" href="#about">SCROLL TO DISCOVER <ArrowDown size={16}/></a></div><aside className="hero-side-note"><span className="eyebrow">DESIGNED WITH INTENT.</span><p>Thoughtful interfaces.<br/>Reliable systems.<br/>A personal approach.</p><a className="text-link" href="#contact">Let’s build together <ArrowUpRight size={16}/></a></aside><div className="hero-index">01 / INTRODUCTION</div></section>
<div className="marquee" aria-label="Core skills"><div>{Array.from({length:2},(_,i)=><span className="marquee-set" key={i} aria-hidden={i===1}>{["React","Node.js","Shopify","Supabase","Liquid","PostgreSQL","TypeScript"].map(name=><TechLabel name={name} key={name}/>)}</span>)}</div></div>
<section id="work" className="section work"><div className="section-top reveal"><div><span className="eyebrow">02 / SELECTED WORK</span><h2>Built with purpose.<br/><span>Designed to stand out.</span></h2></div><p>Business platforms, custom commerce<br/>and thoughtful automation.<br/>A selection of what I’ve been building.</p></div><div className="filters" role="group" aria-label="Filter projects">{['All work','Full stack','Shopify','AI & automation'].map(x=><button key={x} className={category===x?'active':''} onClick={()=>{setCategory(x);setShowAll(false)}}><TechText text={x}/><span>{x==='All work'?projects.length:projects.filter(p=>p.category===x).length}</span></button>)}</div><div className="projects">{visible.map((p,i)=><button className="project" key={p.name} onClick={()=>setSelected(p)}><div className={`project-art${p.category==='Shopify'&&p.image?' storefront-preview':''}`}><Artwork p={p}/><div className="project-open"><ArrowUpRight size={24}/></div><span className="project-index">{String(projects.indexOf(p)+1).padStart(2,'0')}</span></div><div className="project-info"><div><small><TechText text={p.category}/></small><h3>{p.name}</h3></div><span className="project-stack">{p.stack.slice(0,2).map(name=><TechLabel name={name} key={name}/>)}</span></div></button>)}</div>{filtered.length>6&&<button className="more" onClick={()=>setShowAll(!showAll)}>{showAll?'Show selected work':`Explore all ${filtered.length} projects`} <Plus size={18}/></button>}</section>
<section id="expertise" className="section expertise"><div className="section-top reveal"><div><span className="eyebrow">03 / WHAT I BRING</span><h2>One developer.<br/><span>The whole picture.</span></h2></div><span className="expertise-asterisk" aria-hidden="true">✳</span></div><div className="services">{[{title:'Full-stack applications',text:'SaaS platforms, CRMs, admin dashboards and business systems. Interfaces and APIs that work together.',tags:'React · TypeScript · Node.js · Express',icon:'{ }'},{title:'Shopify & e-commerce',text:'Custom Liquid sections, OS 2.0 themes, product and collection pages, responsive storefronts and theme troubleshooting.',tags:'Shopify · Liquid · JavaScript · CSS',icon:'S'},{title:'Backend & data',text:'REST APIs, authentication, role-based access, database design and integrations that support real business workflows.',tags:'PostgreSQL · Supabase · Firebase · MySQL',icon:'↗'},{title:'AI & automation',text:'AI API integrations, voice workflows and data-driven tools that help reduce repetitive work.',tags:'Python · Flask · AI APIs · Workflow automation',icon:'✳'}].map((s,i)=><article className="service reveal" key={s.title}><span className="service-no">0{i+1}</span><div><h3><TechText text={s.title}/></h3><p><TechText text={s.text}/></p><small className="service-stack"><TechText text={s.tags}/></small></div><span className="service-icon">{s.icon==='S'?<BrandLogo name="Shopify"/>:s.icon}</span></article>)}</div><div className="other-tools reveal"><span>ALSO IN MY TOOLKIT</span><p className="toolkit-logos">{["WordPress","Flutter","FlutterFlow","MongoDB","Tailwind CSS","Git","Vercel","Render"].map(name=><TechLabel name={name} key={name}/>)}</p></div></section>
<section id="about" className="section about"><div className="about-left reveal"><span className="eyebrow">04 / THE PERSON BEHIND THE PIXELS</span><h2>A curious mind.<br/>A builder <span>at heart.</span></h2><p>I’m Kumail, a full-stack developer based in Pakistan. I work with clients to turn business requirements into useful, polished digital products.</p><p><TechText text="My work spans React applications, Node.js APIs, database-backed platforms and custom Shopify stores. I care about how a product looks, how it works and how easy it is to use."/></p><div className="education"><span>EDUCATION</span><strong>BS Computer Science</strong><p>University of Southern Punjab · 2022–2026</p></div><a className="text-link" href="https://github.com/kumailraza5" target="_blank" rel="noreferrer">Explore my <TechLabel name="GitHub"/> <ArrowUpRight size={16}/></a></div><div className="journey reveal"><span className="eyebrow">THE JOURNEY</span>{[{date:'PRESENT',title:'Full-stack & Shopify Developer',company:'Independent / Client projects',text:'Web applications, SaaS, custom storefronts, integrations and delivery.'},{date:'2025—2026',title:'FlutterFlow Developer',company:'Team 360',text:'Mobile interfaces, Firebase integration and core workflows for the Madad App.'},{date:'2023—2024',title:'Java Developer',company:'Fiesta Consultants',text:'Progressed from internship to Java development, contributing to desktop application functionality and debugging.'}].map(j=><div className="journey-item" key={j.title}><small>{j.date}</small><h3><TechText text={j.title}/></h3><strong>{j.company}</strong><p><TechText text={j.text}/></p></div>)}</div></section>
<section className="process section"><span className="eyebrow reveal">05 / HOW WE BUILD</span><div className="process-grid">{[['01','Understand','We define the goal, the users and what a successful launch needs.'],['02','Create','I design and build the interface, logic and connected workflows.'],['03','Refine','We review the details, test key flows and prepare for launch.']].map(([n,t,d])=><div className="reveal" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section id="contact" className="section contact"><div className="contact-top"><span className="eyebrow"><span className="dot"/> LET’S MAKE SOMETHING GREAT</span><span>06 / YOUR NEXT CHAPTER</span></div><a className="contact-heading" href={`mailto:${email}`}><h2>Have an idea?<br/><span>Let’s build it.</span></h2><span className="contact-arrow"><ArrowUpRight/></span></a><div className="contact-bottom"><div><p>Tell me what you’re building.<br/>I’ll help you make the next move.</p><a className="email" href={`mailto:${email}`}>{email}</a><button onClick={copy} className="copy" aria-label="Copy email">{copied?<Check size={17}/>:<Copy size={17}/>}</button><small className="copied" role="status">{copied?'Copied!':''}</small></div><div className="socials"><a href="https://github.com/kumailraza5" target="_blank" rel="noreferrer"><BrandLogo name="GitHub"/>GitHub <ArrowUpRight size={14}/></a><a href="https://www.linkedin.com/in/dev-kumail-4440a9261/" target="_blank" rel="noreferrer"><UserRound size={18}/>LinkedIn <ArrowUpRight size={14}/></a><a href="https://www.instagram.com/k.u.m.a.i.l_ra__za/" target="_blank" rel="noreferrer"><Camera size={18}/>Instagram <ArrowUpRight size={14}/></a></div></div></section><footer><a className="brand" href="#home">kr<span>®</span></a><span>© {new Date().getFullYear()} Kumail Raza</span><button className="motion-toggle" onClick={()=>setMotion(!motion)} aria-pressed={!motion}><Orbit size={15}/> Motion {motion?'on':'off'}</button><a href="#home">BACK TO TOP <ArrowUpRight size={15}/></a></footer>
{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="project-title" onClick={e=>e.stopPropagation()}><button autoFocus className="close-modal" onClick={()=>setSelected(null)} aria-label="Close project"><X/></button><div className="modal-art"><Artwork p={selected}/></div><div className="modal-body"><span className="eyebrow"><TechText text={selected.category}/></span><h2 id="project-title">{selected.name}</h2><h3>{selected.subtitle}</h3><p><TechText text={selected.description}/></p><div className="stack">{selected.stack.map(t=><TechLabel name={t} key={t}/>)}</div><ul>{selected.features.map(f=><li key={f}><TechText text={f}/></li>)}</ul><div className="modal-actions">{selected.live&&<a className="pill lime" href={selected.live} target="_blank" rel="noreferrer">View live project <ArrowUpRight size={17}/></a>}{selected.code&&<a className="pill outline" href={selected.code} target="_blank" rel="noreferrer">Source code <GitFork size={17}/></a>}<a className="text-link" href={`mailto:${email}?subject=${encodeURIComponent('Project inquiry: '+selected.name)}`}>Build something like this <ArrowUpRight size={17}/></a></div></div></div></div>}
</main>}
